<img src=http://www.acofi.edu.co/eiei2016/wp-content/uploads/2016/09/Logo-Universidad-ICESI.jpg width="300" height="200" align="center">

#**<big><big>Matemáticas Aplicadas III</big></big><br><small>Ciencias Físicas & Exactas / FIDCA</small><br><small>_*Entrega 5*_ (Bases y subespacios fundamentales de una matriz)**

A continuación se le pide responder por grupo las siguientes preguntas, utilizando una copia del presente cuaderno para consignar todas sus respuestas con el formato requerido.

La entrega está inicialmente para el día **martes 30 de septiembre** y dos **grupos** podría estar encargado de socializar sus resultados de acuerdo a los lineamientos entregados en la sesión del juevez anterior.

**<u>Preguntas</u>**

A continuación encuentra separadas por celda cada pregunta, así usted solo debe continuar escribiendo en la celda para dar cada respuesta. No olvide que todas sus respuestas deben ir acompañadas de al menos un argumento geométrico o numérico y uno algebráico o en lenguaje natural.


1. (16 ptos) **Combinaciones lineales y subespacios**

i. Considere la matriz

$$A=\begin{bmatrix}
1&1&1\\
1&1&1\\
1&1&1
\end{bmatrix}$$

Encuentre dos vectores  $\mathbf{x}$ y $\mathbf{y}$ que formen un conjunto linealmente independiente, y resuelvan $A\mathbf{x}=0$ y $A\mathbf{y}=0$. ¿Que relación tienen estos vectores con el subespacio nulo de $A$, $N(A)$?  ¿Por qué no es necesario preguntar por un tercer vector linealmente independiente tal que $A\mathbf{z} = 0$?

ii. Muestre algebráica y geométricamente que las combinaciones lineales de $v = (1, 1, 0)$ y $w = (0, 1, 1)$ generan un plano en $\mathbb{R}^3$.

(a) Encuentre un vector $z$ que sea perpendicular a $v$ y $w$. Entonces $z$ es perpendicular a todo vector $cv + dw$ en el plano.

(b) Encuentre un vector $u$ que no esté en el plano. Compruebe que $u^T z \not= 0$.

---

##$Solucion$ $i$

Sea
$$
A=\begin{bmatrix}1&1&1\\[4pt]1&1&1\\[4pt]1&1&1\end{bmatrix}.
$$

Para $x=(x_1,x_2,x_3)^T$,
$$
Ax=\begin{bmatrix}x_1+x_2+x_3\\[4pt]x_1+x_2+x_3\\[4pt]x_1+x_2+x_3\end{bmatrix}
=(x_1+x_2+x_3)\begin{bmatrix}1\\[4pt]1\\[4pt]1\end{bmatrix}.
$$

Luego $Ax=0$ si y sólo si
$$
x_1+x_2+x_3=0,
$$
por lo tanto
$$
N(A)=\{(x_1,x_2,x_3)\in\mathbb{R}^3:\;x_1+x_2+x_3=0\}.
$$

Como todas las filas de $A$ son iguales, $\operatorname{rank}(A)=1$ y por rango–nulidad
$$
\dim N(A)=3-\operatorname{rank}(A)=3-1=2.
$$
Así el núcleo es un subespacio de dimensión $2$, por lo que bastan dos vectores independientes para formar una base.

Una forma general de las soluciones es
$$
x=(s,\; t,\; -s-t)=s(1,0,-1)+t(0,1,-1),\qquad s,t\in\mathbb{R}.
$$

Tomemos los vectores
$$
\mathbf{x}=\begin{bmatrix}1\\[4pt]-1\\[4pt]0\end{bmatrix},\qquad
\mathbf{y}=\begin{bmatrix}1\\[4pt]0\\[4pt]-1\end{bmatrix}.
$$
Verificación: $1-1+0=0$ y $1+0-1=0$, por tanto $A\mathbf{x}=A\mathbf{y}=0$.  
Para independencia, suponga $\alpha\mathbf{x}+\beta\mathbf{y}=\mathbf{0}$. Entonces
$$
(\alpha+\beta,\; -\alpha,\; -\beta)=(0,0,0),
$$
de donde $\alpha=\beta=0$. Por tanto $\mathbf{x},\mathbf{y}$ son linealmente independientes y forman una base de $N(A)$.

Los vectores $\mathbf{x}$ y $\mathbf{y}$ resuelven $A\mathbf{x}=0$ y $A\mathbf{y}=0$, pertenecen a $N(A)$ y, al ser independientes en un espacio de dimensión $2$, generan todo $N(A)$. No se pide un tercer vector independiente porque $\dim N(A)=2$ (no existen tres vectores linealmente independientes en $N(A)$).


In [ ]:
from IPython.display import HTML

html_code ="""
<iframe src="https://www.geogebra.org/classic/hgh7arcg?embed" width="800" height="600" allowfullscreen
style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0"></iframe>
"""
display(HTML(html_code))

En el applet de GeoGebra se observa el plano formado por los vectores del espacio nulo de la matriz $A$.
Los vectores dibujados corresponden a una base de $N(A)$, es decir, son linealmente independientes y generan
todo el subespacio solución de $A\mathbf{x}=0$. En la figura puede apreciarse que cualquier combinación lineal
de estos dos vectores permanece dentro del mismo plano, lo cual confirma que $N(A)$ es de dimensión $2$.

---

##$Solucion$ $ii$

Sea
$$
v=(1,1,0),\qquad w=(0,1,1).
$$

La combinación lineal general es
$$
cv+dw=(c,\; c+d,\; d).
$$
Si $(x,y,z)=(c,c+d,d)$ entonces necesariamente se cumple
$$
y=x+z.
$$
Por tanto, el conjunto de todas las combinaciones es
$$
\{(x,y,z)\in\mathbb{R}^3 : y-x-z=0\},
$$
que corresponde a un plano que pasa por el origen. Como está definido por una sola ecuación lineal en $\mathbb{R}^3$, se trata de un subespacio de dimensión $2$ (y no de una recta). En otras palabras, $v$ y $w$ generan un plano y son linealmente independientes.

###$a).$

Para encontrar un vector normal al plano generado por $v$ y $w$, tomamos el producto cruz:
$$
z=v\times w=
\begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k}\\[4pt]
1 & 1 & 0\\[4pt]
0 & 1 & 1
\end{vmatrix}
=(1,-1,1).
$$

Verificamos la perpendicularidad:
$$
v\cdot z=1-1+0=0,\qquad w\cdot z=0-1+1=0.
$$
Así, $z$ es ortogonal a $v$ y $w$ y, en consecuencia, a todo el plano $\operatorname{span}\{v,w\}$.

Geométricamente, $z$ es el **vector normal del plano**. Esto significa que la ecuación cartesiana del plano puede escribirse directamente como
$$
z\cdot (x,y,z)=0
\;\;\Longleftrightarrow\;\;
(x,y,z)\cdot (1,-1,1)=0,
$$
que se reduce a la misma relación $y-x-z=0$.


###$b).$

Tomemos ahora
$$
u=(1,0,0).
$$
Al evaluarlo en la ecuación del plano:
$$
y-x-z=0 \quad \Rightarrow \quad 0-1-0=-1\neq 0,
$$
vemos que $u$ no pertenece al plano.

Además,
$$
u^T z = (1,0,0)\cdot(1,-1,1)=1\neq 0,
$$
lo que confirma que $u$ no es ortogonal a $z$ y, por lo tanto, no puede estar contenido en el plano.

En conclusion, los vectores $v$ y $w$ generan un plano en $\mathbb{R}^3$ descrito por la ecuación $y-x-z=0$. El vector $z=(1,-1,1)$ es el **normal** que caracteriza dicho plano, mientras que cualquier vector como $u=(1,0,0)$ que no satisface la ecuación queda fuera de él.


In [ ]:
from IPython.display import HTML

html_code ="""
<iframe src="https://www.geogebra.org/classic/rjqbjasw?embed" width="800" height="600" allowfullscreen
 style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0"></iframe>

"""
display(HTML(html_code))

En el applet se observa el plano generado por los vectores
$$
v=(1,1,0), \qquad w=(0,1,1),
$$
ambos representados como vectores que parten del origen. Toda combinación lineal $cv+dw$ permanece dentro de este plano, lo cual confirma que $\operatorname{span}\{v,w\}$ es un subespacio bidimensional de $\mathbb{R}^3$.

También se representa el vector
$$
u = v \times w = (1,-1,1),
$$
que es perpendicular tanto a $v$ como a $w$, y por lo tanto perpendicular a todo vector del plano generado por ellos. En el gráfico, $u$ aparece ortogonal al plano, indicando la dirección normal.

Finalmente, se incluye el vector
$$
a=(1,0,0),
$$
el cual no pertenece al plano, ya que no satisface la ecuación $y = x+z$. Además, el producto escalar
$$
a^T u = (1,0,0)\cdot(1,-1,1)=1 \neq 0,
$$
confirma algebraicamente que $a$ no es ortogonal a $u$, y por tanto no está contenido en el plano.

De esta forma, el applet ilustra simultáneamente el plano generado por $\{v,w\}$, su vector normal $u$ y un vector $a$ que se encuentra fuera de dicho subespacio.


#2. (20 ptos) **Subespacios**

i. Describa el espacio columna de $A = \begin{bmatrix}v & w &v + 2w\end{bmatrix}$, donde $u$, $v$ y $w$ son vectores de $\mathbb{R}^3$. Describa el espacio nulo de A: todos los vectores $x = (x_1, x_2, x_3)$ que resuelven $Ax = 0$. Sume las "dimensiones" del plano
(el espacio columna de A) y la recta (el espacio nulo de A) para comprobar que:

dimensión del espacio  columna + dimensión del espacio nulo = número de columnas

ii. Suponga que el espacio columna de una matriz $m\times n$ es todo $\mathbb{R}^3$. ¿Qué se puede decir del valor de $m$? ¿Qué se puede decir del rango $r$ de $A$?

iii. Considere las matrices

$$A_1=\begin{bmatrix}
1&3&-2\\
3&9&-6\\
2&6&-4
\end{bmatrix},\quad A=\begin{bmatrix}
1&2&3\\
4&5&6\\
7&8&9
\end{bmatrix}$$

a. Factorice cada matriz en la forma $𝐴=𝐶𝑅$, donde $𝐶$ es la matriz formada por las columnas de  $𝐴$  que forman un conjunto linealmente independiente y  $𝑅$  la matriz de la forma escalonada reducida de $ 𝐴$.

b. Encuentre una base para el espacio columna de cada matriz $A_i$, calcule la dimensión de cada espacio y los rangos de cada matriz $A_i$.








##i.

Para determinar el espacio columna de $A$ escribimos:

$$Col(A)=\text{span}(v,w,v+2w)$$

Podemos notar que $v+2w$ es una combinación lineal de $v$ y $w$, lo que nos permite reducir el conjunto de generadores a:

$$Col(A)=\text{span}(v,w)$$

De esta forma, el espacio columna de $A$ es un subespacio de dimensión $2$ en $\mathbb{R}^3$.

Ahora determinamos el espacio nulo de $A$. Resolver $Ax=0$ nos lleva a:

$$x_1 v + x_2 w + x_3 (v+2w) = 0$$

$$x_1 v + x_2 w + x_3 v + 2x_3 w = 0$$

$$(x_1+x_3)v + (x_2+2x_3)w=0$$

Para que esta igualdad se cumpla con $v$ y $w \neq 0$, debe ser:

$$x_1=-x_3, \quad x_2=-2x_3$$

Por lo tanto, el espacio nulo está dado por:

$$x = x_3\begin{bmatrix}-1 \\ -2 \\ 1\end{bmatrix}$$

lo que representa un subespacio unidimensional en $\mathbb{R}^3$.

Finalmente, verificamos el teorema rango-nulidad. La dimensión del espacio columna es $2$ y la del espacio nulo es $1$, así que:

$$\dim(Col(A)) + \dim(Null(A)) = 2+1=3$$

Esto confirma que la suma de las dimensiones del espacio columna y del espacio nulo es igual al número de columnas de $A$, cumpliendo el teorema de rango-nulidad.

Si $v$ y $w$ fueran dependientes, el espacio columna tendría dimensión $1$, y en consecuencia el espacio nulo tendría dimensión $2$ para seguir cumpliendo:

$$\dim(Col(A)) + \dim(Null(A)) = 1+2=3$$



##ii.

Si el espacio columna de una matriz $A$ de tamaño $m \times n$ es todo $\mathbb{R}^3$, esto significa que la dimensión del espacio columna, es decir su rango, debe ser igual a $3$. Recordemos que el rango de una matriz no puede ser mayor que el número de filas $m$, por lo que para que el espacio columna sea $\mathbb{R}^3$ se debe cumplir que:

$$m \geq 3$$

ya que si $m < 3$, no habría suficientes filas para generar un espacio de dimensión $3$. Por lo tanto, concluimos que el número de filas debe ser al menos $3$.

Además, el rango $r$ de $A$ es la dimensión del espacio columna. Como el espacio columna es todo $\mathbb{R}^3$, su dimensión es exactamente $3$, de modo que:

$$r = 3$$

Esto significa que $A$ tiene rango completo en el espacio $\mathbb{R}^3$.


## $iii$

### a.

El teorema
### Factorización para $A_1$
Tenemos que las columnas son
$$c1 = \begin{bmatrix}
1\\
3\\
2
\end{bmatrix}$$

$$c2 = \begin{bmatrix}
3\\
9\\
6
\end{bmatrix} = 3\cdot c_1$$

$$c3 = \begin{bmatrix}
-2\\
-6\\
-4
\end{bmatrix} = -2\cdot c_1$$

Como las columnas $c_2$ y $c_3$ son múltiplos de $c_1$, y que $c_3$ es combinación lineal de las otras dos columnas, entonces:
$$C = \begin{bmatrix}
1\\
3\\
2
\end{bmatrix}$$


In [ ]:
# Hallamos la forma escalonada reducida por filas de la matriz para obtener la matriz R
from sympy import *

M = Matrix([[1, 3, -2],
                [3, 9, -6],
                [2, 6, -4]])

M_rref = M.rref()

print("{}".format(M_rref))

Con lo anterior obtenemos que:
$$R= \begin{bmatrix}
1\\
3\\
-2
\end{bmatrix}$$

Por lo que la factorización para $A_1$ de la forma $A=CR$ sería:
$$C=\begin{bmatrix}
-2\\
-6\\
-4
\end{bmatrix},
R=\begin{bmatrix}
1 & 3 & -2\\
\end{bmatrix}$$

$$A_1=\begin{bmatrix}
-2\\
-6\\
-4
\end{bmatrix} \begin{bmatrix}
1 & 3 & -2\\
\end{bmatrix}$$

### Factorización para $A_2$
Tenemos las columnas:
$$c1 = \begin{bmatrix}
1\\
4\\
7
\end{bmatrix}$$

$$c2 = \begin{bmatrix}
2\\
5\\
8
\end{bmatrix}$$

$$c3 = \begin{bmatrix}
3\\
6\\
9
\end{bmatrix}$$

Debemos verificar que $c_1$ y $c_2$ son linealmente independientes y que $c_3 = 2c_2-c_1$. Para esto reducimos por filas en código:

In [ ]:
# Hallamos la forma escalonada reducida por filas de la matriz para obtener la matriz R
from sympy import *

M = Matrix([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

M_rref = M.rref()

print("{}".format(M_rref))

Los pivotes están en las columnas 1 y 2, entonces tomamos $C$ formado por las columnas pivotes originales $[c_1 \; c_2]$ y $R$ como las filas no nulas de la matriz escalonada, de forma que la factorización para $A_2$ es:
$$C=\begin{bmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{bmatrix} ,
R=\begin{bmatrix}
1 & 0 & -1\\
0 & 1 & 2
\end{bmatrix}$$

$$A_2=\begin{bmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{bmatrix} \begin{bmatrix}
1 & 0 & -1\\
0 & 1 & 2
\end{bmatrix}$$

### b.

Primero, debemos considerar el teorema fundamental de la dimensión* el cual afirma que, para una matriz $A$ de tamaño $(m \times n)$:

$$
\dim(\text{Col}(A)) + \dim(\text{Nul}(A)) = n
$$

o,

$$
\operatorname{rank}(A) + \operatorname{nullity}(A) = \text{número de columnas de } A
$$



* Para $(A_1) (3 \times 3)$:

De la factorización obtenida en la respuesta anterior, sabemos que todas las columnas de $(A_1)$ son múltiplos de la primera columna. Por lo tanto una base para el espacio columna de $(A_1)$ es:
$$
\left\{\begin{bmatrix}1 \\ 3 \\ 2\end{bmatrix}\right\}
$$

La dimensión de este espacio (número de vectores en la base) es:
$$
\dim(\text{Col}(A_1)) = 1
$$

Y por ende el rango de la matriz es:
$$
\operatorname{rank}(A_1) = 1
$$

Ahora, aplicando el teorema de rango-nulidad, como $(A_1)$ tiene 3 columnas:

$$
1 + \operatorname{nullity}(A_1) = 3 \quad \Rightarrow \quad \operatorname{nullity}(A_1) = 2.
$$

Esto quiere decir que el espacio nulo de $(A_1)$ es un plano en $\mathbb{R}^3$



* Para $(A_2) (3 \times 3)$:

En la pregunta anterior obtuvimos que las dos primeras columnas de $(A_2)$ son linealmente independientes, y que la tercera columna es combinación lineal de ellas, por lo que una base para el espacio columna de $(A_2)$ es:
$$
\left\{
\begin{bmatrix}1 \\ 4 \\ 7\end{bmatrix},
\begin{bmatrix}2 \\ 5 \\ 8\end{bmatrix}
\right\}
$$

La dimensión de este espacio es:
$$
\dim(\text{Col}(A_2)) = 2
$$

Y el rango de la matriz es:
$$
\operatorname{rank}(A_2) = 2
$$

Aplicando el teorema y como $(A_2)$ también tiene 3 columnas, entonces:

$$
2 + \operatorname{nullity}(A_2) = 3 \quad \Rightarrow \quad \operatorname{nullity}(A_2) = 1
$$

En este caso el espacio nulo de $(A_2)$ es una recta en $\mathbb{R}^3$



# 3. (14 ptos)  **Factorización $LU$**

El método de eliminación Gaussiana paso a paso permite construir la denominada factorización $A=LU$ cuando no es necesario el intercambio de filas. $L$ es una matriz triangular inferior y $U$ una matriz triangular superior. Puede consultar mas detalles de la factorización $LU$ en cualquier texto de algebra lineal, sugiero los textos de Gilbert Strang y Kolman. Mas abajo encontrará un pequeño ejemplo de como encontrar la factorización $LU$ en python. Debe usarla para contestar y argumentar en los siguientes ejercicios.

i. Halle la factorización $LU$ de la matriz $$A=\begin{bmatrix}2 & -1 & 0\\ -1 &2 &-1\\ 0 & -1 & 2\end{bmatrix}.$$

ii. Cuando un cero aparece en la posición de un pivote, la factorización $A=LU$ no es posible!. Verifíquelo para el caso de la matriz $$A=\begin{bmatrix}1 & 1 & 0\\ 1 &1 &2\\ 1 & 2 & 1\end{bmatrix}.$$

Explique brevemente que es una matriz de *permutación* $P$ y muestre que utilizando una matriz $P$ adecuada se puede resolver este problema y obtener la factorización $PA=LU$. ¿Por qué razón un pivote nulo hace imposible la obtención de la factorización $A=LU$?


## i. Hallar la factorización LU

Dada la matriz \( A \):

$$
A = \begin{pmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2
\end{pmatrix}
$$

Queremos descomponer \( A \) en dos matrices: una triangular inferior \( L \) y una triangular superior \( U \), de forma que:

$$
A = LU
$$

donde:

- \( L \) es una matriz triangular inferior con 1s en la diagonal principal.
- \( U \) es una matriz triangular superior.

Comenzamos con la matriz \( A \):

$$
A = \begin{pmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2
\end{pmatrix}
$$

Eliminación gaussiana para convertir \( A \) en una matriz triangular superior \( U \):

#### Primera fila (pivote 2):

Usamos el pivote \( 2 \) en la posición $( A_{11} )$ para eliminar los elementos debajo de él.

1. **Primer elemento de la segunda fila:**
   
$$
L_{21} = \frac{A_{21}}{A_{11}} = \frac{-1}{2} = -0.5
$$

Ahora, sustituimos la segunda fila por la original menos $( L_{21}$) (primera fila):

$$
F_2 = F_2 - L_{21} \times F_1 = \begin{pmatrix} -1 & 2 & -1 \end{pmatrix} - (-0.5) \times \begin{pmatrix} 2 & -1 & 0 \end{pmatrix}
$$

$$
F_2 = \begin{pmatrix} -1 & 2 & -1 \end{pmatrix} + \begin{pmatrix} 1 & -0.5 & 0 \end{pmatrix} = \begin{pmatrix} 0 & 1.5 & -1 \end{pmatrix}
$$

2. **Primer elemento de la tercera fila:**

$$
L_{31} = \frac{A_{31}}{A_{11}} = \frac{0}{2} = 0
$$

No es necesario hacer ningún cambio en la tercera fila.

Matriz \( L \) hasta el momento:

$$
L = \begin{pmatrix}
1 & 0 & 0 \\
-0.5 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

Segunda fila (pivote 1.5):

Ahora, utilizamos el pivote en $( A_{22})$, que es 1.5, para eliminar el elemento debajo de él.

1. **Segundo elemento de la tercera fila:**

$$
L_{32} = \frac{A_{32}}{A_{22}} = \frac{-1}{1.5} = -\frac{2}{3}
$$

Ahora, sustituimos la tercera fila por la original menos $( L_{32})$ (segunda fila):

$$
F_3 = F_3 - L_{32} \times F_2 = \begin{pmatrix} 0 & -1 & 2 \end{pmatrix} - \left(-\frac{2}{3}\right) \times \begin{pmatrix} 0 & 1.5 & -1 \end{pmatrix}
$$

$$
F_3 = \begin{pmatrix} 0 & -1 & 2 \end{pmatrix} + \begin{pmatrix} 0 & -1 & \frac{2}{3} \end{pmatrix} = \begin{pmatrix} 0 & -2 & \frac{8}{3} \end{pmatrix}
$$

Matriz \( L \) final:

$$
L = \begin{pmatrix}
1 & 0 & 0 \\
-0.5 & 1 & 0 \\
0 & -\frac{2}{3} & 1
\end{pmatrix}
$$

Matriz \( U \) final:

$$
U = \begin{pmatrix}
2 & -1 & 0 \\
0 & 1.5 & -1 \\
0 & 0 & \frac{8}{3}
\end{pmatrix}
$$

## ii. El caso cuando el pivote es cero

Si el pivote de alguna columna es cero, necesitamos realizar un intercambio de filas para evitar que la factorización sea imposible. Esto se hace mediante una matriz de permutación \( P \), tal que:

$$
PA = LU
$$

Matriz de permutación \( P \):

La matriz de permutación intercambia las filas cuando un pivote es nulo. En este caso, si el pivote fuera cero, necesitaríamos intercambiar filas para que el pivote sea distinto de cero.

¿Por qué un pivote nulo hace imposible la factorización?:

Un pivote nulo indica que no podemos continuar con el proceso de eliminación sin cambiar el orden de las filas. Esto se debe a que la eliminación de Gauss depende de la división por el pivote, y si el pivote es cero, la división no es posible.


In [ ]:
import pprint
import numpy as np
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)

pprint.pprint(A) #Matriz A

pprint.pprint(P) #Matriz P

pprint.pprint(L) #Matriz L

pprint.pprint(U) #Matriz U

pprint.pprint(np.dot(L,U))#Matriz A = LU

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])
array([[ 7.,  3., -1.,  2.],
       [ 3.,  8.,  1., -4.],
       [-1.,  1.,  4., -1.],
       [ 2., -4., -1.,  6.]])
